# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - covr
  - CholWishart
sudo: false
warnings_are_errors: true
cache: packages
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
os:
  - linux
matrix:
  include:
  - r: devel
  - r: release
    name: "release"
    after_success: Rscript -e 'covr::codecov()'
  - r: oldrel
notifications:
  email:
    - gzthompson@gmail.com

