# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posdefsqrt <- function(x) {
    .Call('_matrixdist_posdefsqrt', PACKAGE = 'matrixdist', x)
}

posdefinvsqrt <- function(x) {
    .Call('_matrixdist_posdefinvsqrt', PACKAGE = 'matrixdist', x)
}

testsymmetric <- function(x, tol) {
    .Call('_matrixdist_testsymmetric', PACKAGE = 'matrixdist', x, tol)
}

dmatnorm_calc <- function(x, mean, U, V) {
    .Call('_matrixdist_dmatnorm_calc', PACKAGE = 'matrixdist', x, mean, U, V)
}

dmat_t_calc <- function(x, df, mean, U, V) {
    .Call('_matrixdist_dmat_t_calc', PACKAGE = 'matrixdist', x, df, mean, U, V)
}

