# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posdefsqrt <- function(x) {
    .Call(`_MixMatrix_posdefsqrt`, x)
}

posdefinvsqrt <- function(x) {
    .Call(`_MixMatrix_posdefinvsqrt`, x)
}

testsymmetric <- function(x, tol) {
    .Call(`_MixMatrix_testsymmetric`, x, tol)
}

dmatnorm_calc <- function(x, mean, U, V) {
    .Call(`_MixMatrix_dmatnorm_calc`, x, mean, U, V)
}

dmat_t_calc <- function(x, df, mean, U, V) {
    .Call(`_MixMatrix_dmat_t_calc`, x, df, mean, U, V)
}

xatx <- function(x, U) {
    .Call(`_MixMatrix_xatx`, x, U)
}

txax <- function(x, U) {
    .Call(`_MixMatrix_txax`, x, U)
}

rmat_inv_t_calc <- function(S, mat, U, V, mean) {
    .Call(`_MixMatrix_rmat_inv_t_calc`, S, mat, U, V, mean)
}

dmat_inv_t_calc <- function(x, df, mean, U, V) {
    .Call(`_MixMatrix_dmat_inv_t_calc`, x, df, mean, U, V)
}

cubeinv <- function(x) {
    .Call(`_MixMatrix_cubeinv`, x)
}

cubemult <- function(x, y) {
    .Call(`_MixMatrix_cubemult`, x, y)
}

detsum <- function(x) {
    .Call(`_MixMatrix_detsum`, x)
}

axbt <- function(a, x, b) {
    .Call(`_MixMatrix_axbt`, a, x, b)
}

